apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://kubernetes.docker.internal:6443
    insecure-skip-tls-verify: true
  name: docker-desktop
- cluster:
    server: https://minikube.local:8443
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
    namespace: default
  name: docker-desktop
- context:
    cluster: minikube
    user: minikube
    namespace: kube-system
  name: minikube
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0tLS1CRUdJTi...
    client-key-data: LS0tLS1CRUdJTi...
- name: minikube
  user:
    client-certificate: /Users/user/.minikube/profiles/minikube/client.crt
    client-key: /Users/user/.minikube/profiles/minikube/client.key
current-context: docker-desktop